import os
import pandas as pd
import yaml

configfile: 'config/data.yaml'

rule get_person:
    input: config['emails'][0]
    output: os.path.join('workflow/results/person_pages.tsv')
    shell: 
        """
        python -m workflow.scripts.find_pure_people --file {input} --top 5
        """

rule get_person_data:
    input: os.path.join('workflow/results/person_pages.tsv')
    output: os.path.join('workflow/results/person_data.tsv')
    shell: 
        """
        python -m workflow.scripts.get_pure_person_data --file {input}
        """

rule get_research_output:
    input: os.path.join('workflow/results/person_pages.tsv')
    output: os.path.join('workflow/results/research_meta_data.tsv')
    shell:
        """
        python -m workflow.scripts.get_pure_research_metadata --file {input}
        """

rule get_research_details:
    input: os.path.join('workflow/results/research_meta_data.tsv')
    output: os.path.join('workflow/results/research_data.complete')
    shell:
        """
        python -m workflow.scripts.get_pure_research_data --file {input}
        """