import os
import pandas as pd
import yaml

configfile: 'config/data.yaml'

PERSON_DATA = 'workflow/results/person_data'
PERSON_METADATA = 'workflow/results/person_metadata'
RESEARCH_DATA = 'workflow/results/research_data'
RESEARCH_METADATA = 'workflow/results/research_metadata'
TEXT_DATA = 'workflow/results/text_data'

rule get_person:
    input: config['emails']
    output: PERSON_DATA
    shell: 
        """
        python -m workflow.scripts.find_pure_people --input {input} --output {output} --top 10
        """

rule get_person_data:
    input: PERSON_DATA
    output: PERSON_METADATA
    shell: 
        """
        python -m workflow.scripts.get_pure_person_data --input {input} --output {output}
        """

rule get_research_output:
    input: PERSON_DATA
    output: RESEARCH_METADATA
    shell:
        """
        python -m workflow.scripts.get_pure_research_metadata --input {input} --output {output}
        """

rule get_research_details:
    input: RESEARCH_METADATA
    output: RESEARCH_DATA
    shell:
        """
        python -m workflow.scripts.get_pure_research_data --input {input} --output {output}
        """

rule parse_text:
    input: RESEARCH_DATA
    output: TEXT_DATA
    shell:
        """
        python -m workflow.scripts.run_spacy --input {input} --output {output}
        """

rule clean_for_build:
    shell:
        """
        echo 'Deleting: workflow/results/*.complete'
        rm -f rm workflow/results/*.complete
        #echo 'Deleting: workflow/results/person*'
        #rm -f rm workflow/results/person*
        """